version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "10:00"
  open-pull-requests-limit: 10
  target-branch: development
  groups:
    github-actions-dependencies:
      patterns:
        - "*"
- package-ecosystem: pip
  directory: "/test"
  schedule:
    interval: weekly
    day: saturday
    time: "10:00"
  open-pull-requests-limit: 10
  target-branch: development
  groups:
    python-dependencies:
      patterns:
        - "*"
